include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: rocm/dev-ubuntu-18.04

test:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - rocm

test:1.4:
  extends:
    - .julia:1.4
    - .test
  tags:
    - rocm

test:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - rocm
  allow_failure: true
