include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: rocm/dev-ubuntu-18.04

# basic tests (LLVM 6)

test:1.0:
  extends:
    - .julia:1.0
    - .test
  tags:
    - rocm

test:1.1:
  extends:
    - .julia:1.1
    - .test
  tags:
    - rocm

test:1.2:
  extends:
    - .julia:1.2
    - .test
  tags:
    - rocm

test:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - rocm

test:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - rocm
  allow_failure: true
